# Generated by Django 4.2.3 on 2024-02-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GetHelp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="фамилия")),
                (
                    "city",
                    models.CharField(max_length=100, verbose_name="город проживания"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="эл почта для связи"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="телефон для связи"),
                ),
                (
                    "social_network",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ссылка на социальную сеть",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=100, verbose_name="тема / заголовок"),
                ),
                ("text", models.TextField(verbose_name="описание проблемы")),
                (
                    "agreed",
                    models.BooleanField(
                        default=False,
                        verbose_name="я согласен на обработку персональных данных",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос на помощь",
                "verbose_name_plural": "Запросы на помощь",
            },
        ),
        migrations.CreateModel(
            name="GiveHelp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="если вы являетесь юр лицом",
                        max_length=128,
                        verbose_name="название юр лица",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="фамилия")),
                (
                    "birthday",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата рождения"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        max_length=100, null=True, verbose_name="страна проживания"
                    ),
                ),
                (
                    "city",
                    models.CharField(max_length=100, verbose_name="город проживания"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="эл почта для связи"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="телефон для связи"),
                ),
                (
                    "social_network",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ссылка на социальную сеть",
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("2-3 часа в неделю", "2-3 часа в неделю"),
                            ("4-7 часов в неделю", "4-7 часов в неделю"),
                            ("Более 7 часов в неделю", "Более 7 часов в неделю"),
                        ],
                        max_length=64,
                        verbose_name="сколько времени в неделю готовы уделять",
                    ),
                ),
                (
                    "help",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Деньгами", "Деньгами"),
                            ("Вещами", "Вещами"),
                            ("Участие", "Участие"),
                            ("Все варианты возможны", "Все варианты возможны"),
                        ],
                        max_length=64,
                        verbose_name="варианты помощи",
                    ),
                ),
                (
                    "mobility",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("На машине", "На машине"),
                            ("Пешком", "Пешком"),
                            ("Оба варианта возможны", "Оба варианта возможны"),
                        ],
                        max_length=64,
                        verbose_name="мобильность",
                    ),
                ),
                ("text", models.TextField(verbose_name="немного о себе")),
                (
                    "agreed",
                    models.BooleanField(
                        default=False,
                        verbose_name="я согласен на обработку персональных данных",
                    ),
                ),
            ],
            options={
                "verbose_name": "Анкета волонтёра",
                "verbose_name_plural": "Анкеты волонтёров",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="заголовок")),
                ("description", models.TextField(verbose_name="текст статьи")),
                ("photo", models.ImageField(blank=True, upload_to="news_photos")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="дата изменения"),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="событие прошло"),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.CreateModel(
            name="Partners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=264, verbose_name="название партнера"),
                ),
                ("about", models.TextField(verbose_name="информация о партнере")),
            ],
            options={
                "verbose_name": "Партнер",
                "verbose_name_plural": "Партнеры",
            },
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, verbose_name="имя категории проекта"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="описание категории проекта"),
                ),
                ("photo", models.ImageField(blank=True, upload_to="project_photos")),
            ],
            options={
                "verbose_name": "Категория проекта",
                "verbose_name_plural": "Категории проектов",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="название проекта"),
                ),
                ("description", models.TextField(verbose_name="описание проекта")),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="краткое описание проекта",
                    ),
                ),
                ("photo", models.ImageField(upload_to="project_photos")),
                (
                    "donation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="необходимая сумма",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.projectcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.CreateModel(
            name="AllYouNeedIs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=32, verbose_name="имя нуждающегося"),
                ),
                (
                    "surname",
                    models.CharField(
                        max_length=32, verbose_name="фамилия нуждающегося"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="город, регион"
                    ),
                ),
                ("description", models.TextField(verbose_name="описание проблемы")),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="краткое описание проблемы",
                    ),
                ),
                ("solution", models.TextField(verbose_name="описание решения")),
                ("photo", models.ImageField(upload_to="needs_photos")),
                (
                    "donation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="необходимая сумма",
                    ),
                ),
                (
                    "collected",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="собрано",
                    ),
                ),
                (
                    "in_process",
                    models.BooleanField(default=True, verbose_name="помощь актуальна"),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="помощь получена"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.projectcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подопечный",
                "verbose_name_plural": "Подопечные",
            },
        ),
    ]
