# Generated by Django 4.2.3 on 2024-02-19 14:03
# Generated by Django 4.2.3 on 2024-02-21 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="заголовок")),
                ("description", models.TextField(verbose_name="текст статьи")),
                ("photo", models.ImageField(blank=True, upload_to="news_photos")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="дата изменения"),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="событие прошло"),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="имя проекта")),
                ("description", models.TextField(verbose_name="описание проекта")),
                ("photo", models.ImageField(blank=True, upload_to="project_photos")),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="имя")),
                ("description", models.TextField(verbose_name="описание задачи")),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="краткое описание задачи",
                    ),
                ),
                ("photo", models.ImageField(upload_to="project_photos")),
                (
                    "donation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="необходимая сумма",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.projectcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
        migrations.CreateModel(
            name="AllYouNeedIs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=32, verbose_name="имя нуждающегося"),
                ),
                (
                    "surname",
                    models.CharField(
                        max_length=32, verbose_name="фамилия нуждающегося"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="город, регион"
                    ),
                ),
                ("description", models.TextField(verbose_name="описание проблемы")),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="краткое описание проблемы",
                    ),
                ),
                ("solution", models.TextField(verbose_name="описание решения")),
                ("photo", models.ImageField(upload_to="needs_photos")),
                (
                    "donation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="необходимая сумма",
                    ),
                ),
                (
                    "collected",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="собрано",
                    ),
                ),
                (
                    "in_process",
                    models.BooleanField(default=True, verbose_name="помощь актуальна"),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="помощь получена"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.projectcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подопечный",
                "verbose_name_plural": "Подопечные",
            },
        ),
    ]
