# Generated by Django 4.2.3 on 2024-03-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="images",
            options={
                "verbose_name": "Фотография",
                "verbose_name_plural": "Фотографии для слайдера новостей",
            },
        ),
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="images/%Y/%m/%d/", verbose_name="фотоальбом"
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.news",
                verbose_name="для новости",
            ),
        ),
    ]
