# Generated by Django 4.2.3 on 2024-02-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='событие прошло'),
        ),
    ]
