# Generated by Django 4.2.3 on 2024-02-27 18:39

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gethelp",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[mainapp.models.validate_phone],
                verbose_name="телефон для связи",
            ),
        ),
        migrations.AlterField(
            model_name="givehelp",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[mainapp.models.validate_phone],
                verbose_name="телефон для связи",
            ),
        ),
    ]
