# Generated by Django 4.2.3 on 2024-02-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Телефон для связи"),
                ),
                ("text", models.TextField(verbose_name="Немного о себе")),
            ],
            options={
                "verbose_name": "Анкета",
                "verbose_name_plural": "Анкеты",
            },
        ),
    ]
