# Generated by Django 4.2.3 on 2024-02-24 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allyouneedis",
            options={
                "ordering": ["id"],
                "verbose_name": "Подопечный",
                "verbose_name_plural": "Подопечные",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["id"],
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["id"],
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
        migrations.AlterModelOptions(
            name="projectcategory",
            options={
                "ordering": ["id"],
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
    ]
