# Generated by Django 4.2.3 on 2024-02-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allyouneedis",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Проект опубликован"),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="краткое описание проекта"
            ),
        ),
    ]
