# Generated by Django 4.2.3 on 2024-02-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_requestcharity_requestvolunteer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allyouneedis",
            options={
                "ordering": ["id"],
                "verbose_name": "Подопечный",
                "verbose_name_plural": "Подопечные",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["id"],
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["id"],
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.AlterModelOptions(
            name="projectcategory",
            options={
                "ordering": ["id"],
                "verbose_name": "Категория проекта",
                "verbose_name_plural": "Категории проектов",
            },
        ),
        migrations.AlterModelOptions(
            name="requestvolunteer",
            options={
                "verbose_name": "Анкета волонтёра",
                "verbose_name_plural": "Анкеты волонтёров",
            },
        ),
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255),
        ),
    ]
