# Generated by Django 4.2.3 on 2024-03-01 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "mainapp",
            "0002_allyouneedis_slug_project_is_published_project_slug_and_more",
        ),
        ("mainapp", "0002_alter_gethelp_phone_alter_givehelp_phone"),
    ]

    operations = []
