# Generated by Django 4.2.3 on 2024-04-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_alter_images_options_alter_images_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="images",
            options={"verbose_name": "Фотография", "verbose_name_plural": "Фотографии"},
        ),
        migrations.RemoveField(
            model_name="images",
            name="post",
        ),
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(
                upload_to="images/%Y/%m/%d/", verbose_name="фотоальбом"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="collected",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="собрано"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="donation",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="необходимая сумма",
            ),
        ),
    ]
