# Generated by Django 4.2.3 on 2024-03-01 10:39

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_alter_gethelp_phone_alter_givehelp_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gethelp",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[mainapp.models.validate_phone],
                verbose_name="телефон для связи в формате +7xxxxxxxxxx",
            ),
        ),
        migrations.AlterField(
            model_name="givehelp",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[mainapp.models.validate_phone],
                verbose_name="телефон для связи в формате +7xxxxxxxxxx",
            ),
        ),
    ]
