# Generated by Django 4.2.3 on 2024-02-18 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_news_is_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя проекта')),
                ('description', models.TextField(verbose_name='описание проекта')),
                ('photo', models.ImageField(blank=True, upload_to='project_photos')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='news_photos'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='имя')),
                ('description', models.TextField(verbose_name='описание задачи')),
                ('short_description', models.CharField(blank=True, max_length=64, verbose_name='краткое описание задачи')),
                ('photo', models.ImageField(upload_to='project_photos')),
                ('donation', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='необходимая сумма')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.projectcategory')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
