# Generated by Django 4.2.3 on 2024-03-01 19:06

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_merge_20240301_2206"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allyouneedis",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="gethelp",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[mainapp.models.validate_phone],
                verbose_name="телефон для связи в формате +7xxxxxxxxxx",
            ),
        ),
        migrations.AlterField(
            model_name="givehelp",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[mainapp.models.validate_phone],
                verbose_name="телефон для связи в формате +7xxxxxxxxxx",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="projectcategory",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
