# Generated by Django 4.2.3 on 2024-02-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_alter_allyouneedis_options_alter_news_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
