# Generated by Django 4.2.3 on 2024-02-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_projectcategory_alter_news_photo_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='donation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='необходимая сумма'),
        ),
    ]
