# Generated by Django 4.2.3 on 2024-02-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_project_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllYouNeedIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='имя нуждающегося')),
                ('surname', models.CharField(max_length=32, verbose_name='фамилия нуждающегося')),
                ('city', models.CharField(max_length=64, verbose_name='город, регион')),
                ('description', models.TextField(verbose_name='описание проблемы')),
                ('short_description', models.CharField(blank=True, max_length=64, verbose_name='краткое описание проблемы')),
                ('solution', models.TextField(verbose_name='описание решения')),
                ('photo', models.ImageField(upload_to='needs_photos')),
                ('donation', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='необходимая сумма')),
                ('in_process', models.BooleanField(default=True, verbose_name='помощь актуальна')),
                ('is_closed', models.BooleanField(default=False, verbose_name='помощь получена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.project')),
            ],
            options={
                'verbose_name': 'Подопечный',
                'verbose_name_plural': 'Подопечные',
            },
        ),
    ]
