# Generated by Django 4.2.3 on 2024-02-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_allyouneedis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allyouneedis',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.projectcategory'),
        ),
    ]
