# Generated by Django 4.2.3 on 2024-02-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_allyouneedis_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allyouneedis',
            name='city',
            field=models.CharField(blank=True, max_length=64, verbose_name='город, регион'),
        ),
        migrations.AlterField(
            model_name='allyouneedis',
            name='short_description',
            field=models.CharField(blank=True, max_length=128, verbose_name='краткое описание проблемы'),
        ),
    ]
