# Generated by Django 4.2.3 on 2024-02-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_allyouneedis_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCharity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=128, verbose_name='название юр лица')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, verbose_name='телефон для связи')),
                ('text', models.TextField(verbose_name='немного о себе')),
            ],
            options={
                'verbose_name': 'Анкета благотворителя',
                'verbose_name_plural': 'Анкеты благотворителей',
            },
        ),
        migrations.CreateModel(
            name='RequestVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=128, verbose_name='название юр лица')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, verbose_name='телефон для связи')),
                ('schedule', models.CharField(blank=True, choices=[('2-3 часа в неделю', '2-3 часа в неделю'), ('4-7 часов в неделю', '4-7 часов в неделю'), ('Более 7 часов в неделю', 'Более 7 часов в неделю')], max_length=64, verbose_name='временные возможности')),
                ('text', models.TextField(verbose_name='немного о себе')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'Категория проекта', 'verbose_name_plural': 'Категории проектов'},
        ),
        migrations.AddField(
            model_name='allyouneedis',
            name='collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='собрано'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='описание проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=128, verbose_name='название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=64, verbose_name='краткое описание проекта'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='description',
            field=models.TextField(verbose_name='описание категории проекта'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(max_length=64, verbose_name='имя категории проекта'),
        ),
    ]
