# Generated by Django 4.2.3 on 2024-02-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_requestcharity_requestvolunteer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcharity',
            name='help',
            field=models.CharField(blank=True, choices=[('Деньгами', 'Деньгами'), ('Вещами', 'Вещами'), ('Оба варианта возможны', 'Оба варианта возможны')], max_length=64, verbose_name='варианты помощи'),
        ),
        migrations.AddField(
            model_name='requestvolunteer',
            name='mobility',
            field=models.CharField(blank=True, choices=[('На машине', 'На машине'), ('Пешком', 'Пешком'), ('Оба варианта возможны', 'Оба варианта возможны')], max_length=64, verbose_name='мобильность'),
        ),
    ]
