# Generated by Django 4.2.3 on 2023-07-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='Ник')),
                ('telegram_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Телеграм')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('birthdate', models.DateField(null=True, verbose_name='Дата рождения')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
